---

- name: install requirements
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - git
    - nodejs
    - openjdk-11-jdk

- name: install npm
  include_role:
    name: robertdebock.npm
