---

- name: install docker
  command: bash -c "curl -fsSL https://get.docker.com/ | sh"

- name: install requirements
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - git
    - nodejs
    - openjdk-11-jdk
    - docker-compose


- name: Install Angular CLI
  npm:
    name: "@angular/cli"
    global: yes
    state: present
  failed_when: false
