version: '2'
services:
  product:
    build:
      context: product
      dockerfile: Dockerfile
    image: product
    container_name: product
    ports:
      - "8070:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    links:
      - product-postgres:product-bdd
      - keycloak:keycloak
  order-1:
    build:
      context: order
      dockerfile: Dockerfile
    image: order
    container_name: order-1
    ports:
      - "8071:8080"
    links:
      - order-postgres:order-bdd
      - keycloak:keycloak
    environment:
      server_name: "order-1"
      SPRING_PROFILES_ACTIVE: prod

  order-2:
    build:
      context: order
      dockerfile: Dockerfile
    image: order
    container_name: order-2
    ports:
      - "8073:8080"
    links:
      - order-postgres:order-bdd
      - keycloak:keycloak
    environment:
      server_name: "order-2"
      SPRING_PROFILES_ACTIVE: prod

  ecom-elite-front:
    build:
      context: ecom-elite-front
      dockerfile: Dockerfile
    container_name: ecom-elite-front
    image: ecom-elite-front
    links:
      - product:product-api
      - order-1:order-1-api
      - order-2:order-2-api
      - keycloak:keycloak
    ports:
      - "8072:80"
    volumes:
      - ./ecom-elite-front/conf:/etc/nginx/conf.d/

  order-postgres:
    image: postgres
    container_name: order-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=order
  product-postgres:
    image: postgres
    container_name: product-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=product


  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8074:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/import/ecom.json
    user: root
    volumes:
      - ./realms/ecom.json:/import/ecom.json
