apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  labels:
    application: keycloak
    type: auth-server
spec:
  containers:
    - name: keycloak
      image: jboss/keycloak
      imagePullPolicy: IfNotPresent
      env:
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: KEYCLOAK_IMPORT
          value: /import/ecom.json
      volumeMounts:
        - mountPath: /import/
          name: kc-configuration
      ports:
        - containerPort: 8080
  volumes:
    - name: kc-configuration
      hostPath:
        path: /c/Users/Mahdi/Documents/ecom-elite/kubernetes/pods/config
