apiVersion: v1
kind: Pod
metadata:
  name: front
  labels:
    application: front
    type: front-end
spec:
  containers:
    - name: front
      image: ecom-elite-front
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-configuration
  volumes:
    - name: nginx-configuration
      hostPath:
        path: /c/Users/Mahdi/Documents/ecom-elite/kubernetes/pods/nginx-conf
