apiVersion: v1
kind: Secret
metadata:
  name: product-secrets
type: Opaque
data:
  db.url: amRiYzpwb3N0Z3Jlc3FsOi8vcHJvZHVjdC1kYi1zdmM6NTQzMi9wb3N0Z3Jlcw==
  db.username: cG9zdGdyZXM=
  db.password: cHJvZHVjdA==

